### ISSUE TITLE
Appeal for High-Resolution Versions!

### ISSUE THREAD

**Issue by xivid** [MKimiSH/ETH-exam-cheat-sheets#1]
LONG LIVE THE KING OF 6.0!
Please provide high-resolution versions so that we can take a step closer to the great ZHANXIAN! Thanks a lot!

**Comment by MKimiSH** [comment]
Your extensive exaggeration is not appreciated and I want to be as good a programmer as you are. Still, please specify the files that are not high-res enough so that I can re-photo them....

**Comment by xivid** [comment]
The Statistical Learning Theory ones are perfect. Others may have been compressed too much...

**Comment by MKimiSH** [comment]
Okay, I see. I think the reason is that SLT was the only one that I didn't need to worry about the space, since it allowed the course script (50+ pages) to be taken to the exam... Thus the font is larger.

**Comment by MKimiSH** [comment]
What do you think now? Check `red-high-res` branch

**Comment by xivid** [comment]
Excellent. It's much better now.

**Comment by MKimiSH** [comment]
Merged.. #2
